blog/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from django.views.static import serve
from blog import settings
from app01 import views as app_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('weixin', app_views.weixin_main),
    path('login/', app_views.log_in, name='login'),
    path('logout/', app_views.log_out, name='logout'),
    path('register/', app_views.register, name='register'),
    path('index/', app_views.index),
    path('get_valid_img/', app_views.get_valid_img, name='get_valid_img'),
    re_path(r'^$', app_views.index),
    re_path(r'blog/',include('app01.urls')),
    # media配置
    re_path(r'media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

app01/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class UserInfo(AbstractUser):
    """
    用户信息
    """
    nid = models.AutoField(primary_key=True)
    telephone = models.CharField(max_length=11,null=True,unique=True)
    avatar = models.FileField(upload_to='avatar/',default='avatar/default.png')
    create_time = models.DateTimeField(verbose_name='创建时间',auto_now_add=True)

    # blog = models.OneToOneField(to='Blog',to_field='nid',null=True,on_delete=models.CASCADE)

    def __str__(self):
        return self.username


class Blog(models.Model):
    """
    博客信息
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='个人博客标题',max_length=64)
    site_name = models.CharField(verbose_name='站点名称',max_length=64)
    theme = models.CharField(verbose_name='博客主题',max_length=32)
    user = models.OneToOneField(to='UserInfo', to_field='nid', null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class Category(models.Model):
    """
    博客个人文章分类表
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='分类标题', max_length=32)
    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid', on_delete=models.CASCADE)

    def __str__(self):
        return self.title + '-->' + self.blog.user.username

class Tag(models.Model):
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='标签名称', max_length=32)
    blog = models.ForeignKey(verbose_name='所属博客', to='Blog', to_field='nid', on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class Article(models.Model):
    nid = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name='文章标题', max_length=50)
    desc = models.CharField(verbose_name='文章描述', max_length=255)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    content = models.TextField()

    comment_count = models.IntegerField(default=0)
    up_count = models.IntegerField(default=0)
    down_count = models.IntegerField(default=0)

    user = models.ForeignKey(verbose_name='作者', to='UserInfo', to_field='nid', on_delete=models.CASCADE)
    category = models.ForeignKey(verbose_name='文章分类', to='Category', to_field='nid', null=True, on_delete=models.CASCADE)
    tags  = models.ManyToManyField(
        to='Tag',
        through='Article2Tag',
        through_fields=('article', 'tag'),
    )

    def __str__(self):
        return self.title + '-->' + self.user.username

class Article2Tag(models.Model):
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(verbose_name='文章', to='Article', to_field='nid', on_delete=models.CASCADE)
    tag = models.ForeignKey(verbose_name='标签', to='Tag', to_field='nid', on_delete=models.CASCADE)

    class Meta:
        unique_together = [
            ('article', 'tag'),
        ]

    def __str__(self):
        return self.article.title + '-->' + self.tag.title


class ArticleUpDown(models.Model):
    """
    点赞表
    """
    nid = models.AutoField(primary_key=True)
    user = models.ForeignKey('UserInfo', null=True, on_delete=models.CASCADE)
    article = models.ForeignKey('Article', null=True, on_delete=models.CASCADE)
    is_up = models.BooleanField(default=True)

    class Meta:
        unique_together = [
            ('article', 'user'),
        ]

class Comment(models.Model):
    """
    评论表
    """
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(verbose_name='评论文章', to='Article', to_field='nid', on_delete=models.CASCADE)
    user = models.ForeignKey(verbose_name='评论者', to='UserInfo', to_field='nid', on_delete=models.CASCADE)
    content = models.CharField(verbose_name='评论内容', max_length=255)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    parent_comment = models.ForeignKey('self', null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.content

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %} {{ title|default:"首页" }} {% endblock %}</title>

	<!-- bootstrap -->
	<link rel="stylesheet" href="{% static 'blog/bs/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'blog/bs/css/custom.css' %}">

	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/jquery.cookie.js' %}"></script>
    <style>
        *{
            margin: 0;
            padding: 0;
        }
        body{
            padding-top: 70px;
        }

    </style>
    {% block sstyle %} {% endblock %}
</head>
<body>
<nav class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
		<div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
			<a class="navbar-brand" href="/index/">博客园</a>
		</div>
        <div id="navbar" class="navbar-collapse collapse" aria-expanded="false">
            <ul class="nav navbar-nav">
				<li><a href="/index/">首页</a></li>
                <li><a href="#">新闻</a></li>
                <li><a href="#">博文</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
           {% if request.user.is_authenticated %}
            <li><a href="#">当前用户：{{ request.user }}</a></li>
                    <li class="divider"></li>
                    <li><a href="/blog/blog_manage/">管理</a></li>
                    <li class="divider"></li>
                    <li><a href="{% url 'logout' %}">登出</a></li>
            {% else %}
                {% block login_content %}
                <li><a href="{% url 'login' %}">登录</a></li>
                <li><a href="{% url 'register' %}">注册</a></li>
                {% endblock %}
            {% endif%}
            </ul>
        </div>
    </div>
</nav>
<div class="container-fluid">
        <div class="row">
            {% block content %}

            {% endblock %}
        </div>
        <hr>
        <div class="row">
            <div class="text-center">
            <p> Powered By <a href="/admin/">Django 1.11.8</a></p>
            <p> Copyright 2018. Cnpe 深圳市卫宁信息技术有限公司</p>
	    <p> 工商部域名备案许可证号：粤ICP备11060402号-3</p>
            </div>
        </div>
</div>
</body>
{% block js %}

{% endblock %}
</html>

templates/index.html
{% extends 'base.html' %}

{% block sstyle %}
    <style>
         .avatar_img,.desc{
             float: left;
         }

        .info .timer{

            color: darkgray;
        }
        .info{
            margin-top: 10px;
            font-size: 12px;
        }
        .desc{
            font-size: 14px;
            margin-left: 10px;
            text-align: justify;
        }

    </style>
{% endblock %}
{% block content %}
<div class="row">
        <div class="col-md-3">
            <div class="panel panel-warning">
                <div class="panel-heading">Panel heading without title</div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>

            <div class="panel panel-info">
                <div class="panel-heading">Panel heading without title</div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>

            <div class="panel panel-danger">
                <div class="panel-heading">Panel heading without title</div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>

        </div>
        <div class="col-md-6">
            <div class="article_list">
                {% for article in article_list %}
                <div class="article-item small">
                    <h5><a href="/blog/{{ article.user.username }}/articles/{{ article.pk }}">{{ article.title }}</a></h5>
                    <div class="row">
                           <div class="avatar_img col-md-1">
                               <a href="/blog/{{ article.user.username }}/">
                                   <img src="{{ article.user.avatar.url }}" alt="" width="60" height="60">
                               </a>
                           </div>
                           <div class="desc col-md-10">{{ article.desc }}</div>
                       </div>

                      <div class="info">
                          <span><a href="/blog/{{ article.user.username }}/">{{ article.user.username }}</a> 发布于</span>
                          <span class="timer">{{ article.create_time|date:"Y-m-d H:i" }}</span>&nbsp;&nbsp;
                          <span class="glyphicon glyphicon-comment"></span>&nbsp;<span>评论({{ article.comment_count }})</span>
                          <span class="glyphicon glyphicon-thumbs-up"></span>&nbsp;<span>点赞({{ article.up_count }})</span>
                      </div>
                </div>
                    <hr>
                {% endfor %}
            </div>
            <!---分页-->
                <ul class="pagination">
                    {{ page_html }}
                  </ul>
                <!---分页end---->
        </div>
        <div class="col-md-3">
            <div class="panel panel-primary">
                <div class="panel-heading">Panel heading without title</div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">Panel heading without title</div>
                <div class="panel-body">
                    Panel content
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block title %}
登录
{% endblock %}

{% block login_content %}
    <li><a href="{% url 'register' %}">注册</a></li>
{% endblock %}

{% block content %}
<div class="col-md-6 col-md-push-3">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">登录</h3>
        </div>
        <div class="panel-body">
            <form class="form-horizontal">
                {% csrf_token %}
                <div class="form-group form-group-sm">
                    <label for="user" class="col-sm-2 control-label">用户名</label>
                    <div class="col-sm-10">
                        {{ loginForm.user }} <span></span>
                    </div>
                </div>
                <div class="form-group form-group-sm">
                    <label for="pwd" class="col-sm-2 control-label">密码</label>
                    <div class="col-sm-10">
                        {{ loginForm.pwd }}<span></span>
                    </div>
                </div>
                <div class="form-group form-group-sm">
                    <label for="valid_code" class="col-sm-2 control-label">验证码</label>
                    <div class="col-sm-10">
                        <div class="row">
                            <div class="col-sm-6">
                                {{ loginForm.valid_code }}<span></span>
                            </div>
                            <div class="col-sm-6">
                                <img src="{% url 'get_valid_img' %}" width="210" height="40" id="valid_img">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group form-group-sm">
                    <div class="col-sm-offset-2 col-sm-10">
                        <div class="checkbox">
                            <label>
                                <input type="checkbox"> 记住我
                            </label>
                        </div>
                    </div>
                  </div>
                <div class="form-group form-group-sm">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="button" class="btn btn-default login_btn">提交</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
    <script>
        $('#valid_img').click(function () {
            $(this)[0].src += '?'
        });

        $('.login_btn').click(function () {
            $.ajax({
                url:'{% url "login" %}',
                type:'post',
                data:{
                    csrfmiddlewaretoken:$('[name="csrfmiddlewaretoken"]').val(),
                    user:$('#id_user').val(),
                    pwd:$('#id_pwd').val(),
                    valid_code:$('#id_valid_code').val()
                },
                success:function (data) {
                    if(data.user){
                        location.href = '{{ next_url }}';
                    }else{
                        $('span').html('');
                        $('.form-group span ').parent().removeClass('has-error');
                        $.each(data.error_msg,function (k,v) {
                            $('#id_'+k).next().css('color','red').html(v[0]).parent().addClass('has-error');
                        })
                    }
                }
            })
        })
    </script>

{% endblock %}

templates/register.html
{% extends 'base.html' %}

{% block title %}
注册
{% endblock %}

{% block login_content %}
    <li><a href="{% url 'login' %}">登录</a></li>
{% endblock %}

{% block content %}
<div class="col-md-6 col-md-push-3">
    <div class="panel panel-info">
        <div class="panel-heading">
            <h3 class="panel-title">注册</h3>
        </div>
        <div class="panel-body">
            <form class="form-horizontal">
                {% csrf_token %}
                <div class="form-group form-group-sm">
                    <label for="user" class="col-sm-2 control-label">用户名</label>
                    <div class="col-sm-10">
                        {{ regForm.user }} <span></span>
                    </div>
                </div>
                <div class="form-group form-group-sm">
                    <label for="pwd" class="col-sm-2 control-label">密码</label>
                    <div class="col-sm-10">
                        {{ regForm.pwd }} <span></span>
                    </div>
                </div>
                <div class="form-group form-group-sm">
                    <label for="repeat_pwd" class="col-sm-2 control-label">确认密码</label>
                    <div class="col-sm-10">
                    {{ regForm.repeat_pwd }} <span></span>
                    </div>
                </div>
                <div class="form-group form-group-sm">
                    <label for="email" class="col-sm-2 control-label">邮箱</label>
                    <div class="col-sm-10">
                        {{ regForm.email }} <span></span>
                    </div>
                </div>
                <div class="form-group form-group-sm">
                    <label for="avatar" class="col-sm-2 control-label">头像</label>
                    <div class="col-sm-10">
                        <div class="avatar_box">
                            <img src="/static/blog/img/default.png" alt="" id="avatar_img">
                            <input type="file" class="form-control" id="avatar_file">
                        </div>
                    </div>
                </div>
                <div class="form-group form-group-sm">
                    <label for="valid_code" class="col-sm-2 control-label">验证码</label>
                    <div class="col-sm-10">
                        <div class="row">
                            <div class="col-sm-6">
                                {{ regForm.valid_code }} <span></span>
                            </div>
                            <div class="col-sm-6">
                                <img src="{% url 'get_valid_img' %}" width="210" height="40" id="valid_img">
                            </div>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="button" class="btn btn-default reg_btn">提交</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
    <script>
        $('#valid_img').click(function () {
            $(this)[0].src += '?';
        });
        $('#avatar_file').change(function () {
           var file = $(this)[0].files[0];
           var reader = new FileReader();
           reader.readAsDataURL(file);
           reader.onload = function () {
               $('#avatar_img').attr('src',this.result);
           };
        });
        $('.reg_btn').click(function () {
            var $formData = new FormData();
            $formData.append('user',$('#id_user').val());
            $formData.append('pwd',$('#id_pwd').val());
            $formData.append('repeat_pwd',$('#id_repeat_pwd').val());
            $formData.append('email',$('#id_email').val());
            $formData.append('csrfmiddlewaretoken',$('[name="csrfmiddlewaretoken"]').val());
            $formData.append('valid_code',$('#id_valid_code').val());
            $formData.append('file_img',$('#avatar_file')[0].files[0]);
            $.ajax({
                url:'{% url "register" %}',
                type:'post',
                data:$formData,
                processData:false,
                contentType:false,
                success:function (data) {
                    if(data.user){
                        location.href = '{% url "login" %}';
                    }else{
                        $('span').html('');
                        $('.form-group span').parent().removeClass('has-error');
                        $.each(data.errors,function (k,v) {
                            $('#id_'+k).next().css('color','red').html(v[0]).parent().addClass('has-error');
                        })
                    }
                }
            });
        })
    </script>
{% endblock %}